server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_buffering off;
        proxy_read_timeout 30s;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
